[project]
name = "ontopipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = ["symbolicai"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
symbolicai = { git = "https://github.com/ExtensityAI/symbolicai.git", rev = "594d1894a8d3713533690baed864aaa7c179d6fe" } # fixed commit hash, update if needed

[tool.uv.workspace]
members = ["packages/eval"]
