[project]
name = "ontopipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = ["symbolicai"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
symbolicai = { git = "https://github.com/ExtensityAI/symbolicai.git", rev = "13e8bd1d44e0d73263f20ae31c700a256470886c" } # fixed commit hash, update if needed

[tool.uv.workspace]
members = ["packages/eval"]
