[project]
name = "eval"
version = "0.1.0"
description = "Evaluation framework for ontopipe"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = ["ontopipe", "evaluate==0.4.3", "neo4j==5.28.1"]

[tool.uv.sources]
ontopipe = { workspace = true }

[project.scripts]
eval = "eval.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
